# Generated by Django 5.1.6 on 2025-02-16 07:03

import CarApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0002_car_chassisnumber_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='chassisnumber',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[CarApp.models.alphanumeric]),
        ),
    ]
