# Generated by Django 5.1.6 on 2025-02-16 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0003_showroom_alter_car_chassisnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='showroom_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Showrooms', to='CarApp.showroom'),
        ),
    ]
